/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Who5RouteImport } from './routes/who5'
import { Route as IndexRouteImport } from './routes/index'

const Who5Route = Who5RouteImport.update({
  id: '/who5',
  path: '/who5',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/who5': typeof Who5Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/who5': typeof Who5Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/who5': typeof Who5Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/who5'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/who5'
  id: '__root__' | '/' | '/who5'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Who5Route: typeof Who5Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/who5': {
      id: '/who5'
      path: '/who5'
      fullPath: '/who5'
      preLoaderRoute: typeof Who5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Who5Route: Who5Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
