/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Who5RouteImport } from './routes/who5'
import { Route as WheelRouteImport } from './routes/wheel'
import { Route as PsycheRouteImport } from './routes/psyche'
import { Route as MethodRouteImport } from './routes/method'
import { Route as ForYouRouteImport } from './routes/for-you'
import { Route as CrossCultureRouteImport } from './routes/cross-culture'
import { Route as CounsellingRouteImport } from './routes/counselling'
import { Route as CoreRouteImport } from './routes/core'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AffiliateStatusRouteImport } from './routes/affiliate.status'

const Who5Route = Who5RouteImport.update({
  id: '/who5',
  path: '/who5',
  getParentRoute: () => rootRouteImport,
} as any)
const WheelRoute = WheelRouteImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => rootRouteImport,
} as any)
const PsycheRoute = PsycheRouteImport.update({
  id: '/psyche',
  path: '/psyche',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const ForYouRoute = ForYouRouteImport.update({
  id: '/for-you',
  path: '/for-you',
  getParentRoute: () => rootRouteImport,
} as any)
const CrossCultureRoute = CrossCultureRouteImport.update({
  id: '/cross-culture',
  path: '/cross-culture',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellingRoute = CounsellingRouteImport.update({
  id: '/counselling',
  path: '/counselling',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreRoute = CoreRouteImport.update({
  id: '/core',
  path: '/core',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateStatusRoute = AffiliateStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AffiliateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRouteWithChildren
  '/coaching': typeof CoachingRoute
  '/contact': typeof ContactRoute
  '/core': typeof CoreRoute
  '/counselling': typeof CounsellingRoute
  '/cross-culture': typeof CrossCultureRoute
  '/for-you': typeof ForYouRoute
  '/method': typeof MethodRoute
  '/psyche': typeof PsycheRoute
  '/wheel': typeof WheelRoute
  '/who5': typeof Who5Route
  '/affiliate/status': typeof AffiliateStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRouteWithChildren
  '/coaching': typeof CoachingRoute
  '/contact': typeof ContactRoute
  '/core': typeof CoreRoute
  '/counselling': typeof CounsellingRoute
  '/cross-culture': typeof CrossCultureRoute
  '/for-you': typeof ForYouRoute
  '/method': typeof MethodRoute
  '/psyche': typeof PsycheRoute
  '/wheel': typeof WheelRoute
  '/who5': typeof Who5Route
  '/affiliate/status': typeof AffiliateStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRouteWithChildren
  '/coaching': typeof CoachingRoute
  '/contact': typeof ContactRoute
  '/core': typeof CoreRoute
  '/counselling': typeof CounsellingRoute
  '/cross-culture': typeof CrossCultureRoute
  '/for-you': typeof ForYouRoute
  '/method': typeof MethodRoute
  '/psyche': typeof PsycheRoute
  '/wheel': typeof WheelRoute
  '/who5': typeof Who5Route
  '/affiliate/status': typeof AffiliateStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate'
    | '/coaching'
    | '/contact'
    | '/core'
    | '/counselling'
    | '/cross-culture'
    | '/for-you'
    | '/method'
    | '/psyche'
    | '/wheel'
    | '/who5'
    | '/affiliate/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate'
    | '/coaching'
    | '/contact'
    | '/core'
    | '/counselling'
    | '/cross-culture'
    | '/for-you'
    | '/method'
    | '/psyche'
    | '/wheel'
    | '/who5'
    | '/affiliate/status'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affiliate'
    | '/coaching'
    | '/contact'
    | '/core'
    | '/counselling'
    | '/cross-culture'
    | '/for-you'
    | '/method'
    | '/psyche'
    | '/wheel'
    | '/who5'
    | '/affiliate/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffiliateRoute: typeof AffiliateRouteWithChildren
  CoachingRoute: typeof CoachingRoute
  ContactRoute: typeof ContactRoute
  CoreRoute: typeof CoreRoute
  CounsellingRoute: typeof CounsellingRoute
  CrossCultureRoute: typeof CrossCultureRoute
  ForYouRoute: typeof ForYouRoute
  MethodRoute: typeof MethodRoute
  PsycheRoute: typeof PsycheRoute
  WheelRoute: typeof WheelRoute
  Who5Route: typeof Who5Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/who5': {
      id: '/who5'
      path: '/who5'
      fullPath: '/who5'
      preLoaderRoute: typeof Who5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wheel': {
      id: '/wheel'
      path: '/wheel'
      fullPath: '/wheel'
      preLoaderRoute: typeof WheelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psyche': {
      id: '/psyche'
      path: '/psyche'
      fullPath: '/psyche'
      preLoaderRoute: typeof PsycheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-you': {
      id: '/for-you'
      path: '/for-you'
      fullPath: '/for-you'
      preLoaderRoute: typeof ForYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-culture': {
      id: '/cross-culture'
      path: '/cross-culture'
      fullPath: '/cross-culture'
      preLoaderRoute: typeof CrossCultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counselling': {
      id: '/counselling'
      path: '/counselling'
      fullPath: '/counselling'
      preLoaderRoute: typeof CounsellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core': {
      id: '/core'
      path: '/core'
      fullPath: '/core'
      preLoaderRoute: typeof CoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate/status': {
      id: '/affiliate/status'
      path: '/status'
      fullPath: '/affiliate/status'
      preLoaderRoute: typeof AffiliateStatusRouteImport
      parentRoute: typeof AffiliateRoute
    }
  }
}

interface AffiliateRouteChildren {
  AffiliateStatusRoute: typeof AffiliateStatusRoute
}

const AffiliateRouteChildren: AffiliateRouteChildren = {
  AffiliateStatusRoute: AffiliateStatusRoute,
}

const AffiliateRouteWithChildren = AffiliateRoute._addFileChildren(
  AffiliateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffiliateRoute: AffiliateRouteWithChildren,
  CoachingRoute: CoachingRoute,
  ContactRoute: ContactRoute,
  CoreRoute: CoreRoute,
  CounsellingRoute: CounsellingRoute,
  CrossCultureRoute: CrossCultureRoute,
  ForYouRoute: ForYouRoute,
  MethodRoute: MethodRoute,
  PsycheRoute: PsycheRoute,
  WheelRoute: WheelRoute,
  Who5Route: Who5Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
